# Generated by Django 4.2 on 2023-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.AddField(
            model_name="post",
            name="num_of_read",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("p", "Publish")],
                default="p",
                help_text="blog status",
                max_length=1,
            ),
        ),
    ]
