# Generated by Django 4.2 on 2023-04-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_post_slug_post_num_of_read_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to="myapp.comment",
            ),
        ),
    ]
