# Generated by Django 4.2 on 2023-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="myapp/images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="myapp.category"),
        ),
    ]
