# Generated by Django 4.2 on 2023-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_post_image_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                height_field=223, null=True, upload_to="myapp/images", width_field=350
            ),
        ),
    ]
