# Generated by Django 4.2 on 2023-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img_height",
            field=models.PositiveIntegerField(blank=True, default="223", null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="img_width",
            field=models.PositiveIntegerField(blank=True, default="350", null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                height_field="img_height",
                null=True,
                upload_to="myapp/images",
                width_field="img_width",
            ),
        ),
    ]
