# Generated by Django 4.2 on 2023-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, default="anonymous", max_length=50),
        ),
    ]
